name: Trigger CircleCI

on:
  pull_request:
    types: [opened, synchronize]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Test-Deploy
        id: test-deploy-workflow
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.6
        env:
          CCI_TOKEN: ${{ secrets.CIRCLE_PERSONAL_TOKEN }}
      - name: Test-Module-Upgrade
        id: test-upgrade-workflow
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.6
        env:
          CCI_TOKEN: ${{ secrets.CIRCLE_PERSONAL_TOKEN }}

